name: Snyk Security Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installer Snyk et analyser les dépendances
      - name: Run Snyk vulnerability scan
        uses: snyk/actions@v1
        with:
          args: test --all-projects --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
